blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='detail'),
	url(r'^archives/(?P<year>\d{4})/(?P<month>\d{1,2})/$', views.ArchivesView.as_view(), name='archives'),
	url(r'^category/(?P<pk>\d+)/$', views.CategoryView.as_view(), name='category'),
	url(r'^tag/(?P<pk>\d+)/$', views.TagView.as_view(), name='tag'),
	# url(r'^search/$', views.search, name='search'),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'', include('blog.urls')),
	url(r'', include('comments.urls')),
	# url(r'^all/rss/$', AllPostsRssFeed(), name='rss')
	url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
	url(r'^search/', include('haystack.urls'))
]

comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blog/models.py
import markdown

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
from django.utils.html import strip_tags


@python_2_unicode_compatible
class Category(models.Model):
	name = models.CharField(max_length=100)

	# def __unicode__(self):
	def __str__(self):
		return self.name


@python_2_unicode_compatible
class Tag(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name


@python_2_unicode_compatible
class Post(models.Model):
	title = models.CharField(max_length=70)
	body = models.TextField()
	created_time = models.DateTimeField()
	modified_time = models.DateTimeField()
	excerpt = models.CharField(max_length=200, blank=True)
	category = models.ForeignKey(Category)
	tags = models.ManyToManyField(Tag, blank=True)
	author = models.ForeignKey(User)

	views = models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:detail', kwargs={'pk': self.pk})

	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])

	def save(self, *args, **kwargs):
		if not self.excerpt:
			md = markdown.Markdown(
				extensions=[
					'markdown.extensions.extra',
					'markdown.extensions.codehilite',
				]
			)
			self.excerpt = strip_tags(md.convert(self.body)[:100])
		super(Post, self).save(*args, **kwargs)

	class Meta:
		ordering = ['-created_time']

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible


# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blog/views.py
# from django.http import HttpResponse
import markdown
from django.shortcuts import render, get_object_or_404
from .models import Post, Category, Tag
from comments.forms import CommentForm
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.db.models import Q


def search(request):
	q = request.GET.get('q')
	error_msg = ''
	if not q:
		error_msg = '请输入关键词'
		return render(request, 'blog/index.html', {'error_msg': error_msg})

	post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
	return render(request, 'blog/index.html', {'error_msg': error_msg, 'post_list': post_list})


class IndexView(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'
	paginate_by = 3

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')
		pagination_data = self.pagination_data(paginator, page, is_paginated)
		context.update(pagination_data)

		return context


	def pagination_data(self, paginator, page, is_paginated):
		if not is_paginated:
			return {}
		# 当前页左边连续的页码号，初始值为空
		left = []
		right = []

		# 标示第 1 页页码后是否需要显示省略号
		left_has_more = False
		right_has_more = False

		# 是否需要显示第一页
		first = False
		last = False

		# 用户请求的当前页码
		page_number = page.number

		total_pages = paginator.num_pages

		# 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
		page_range = paginator.page_range

		if page_number == 1:
			right = page_range[page_number:page_number+2]

			if right[-1] < total_pages - 1:
				right_has_more = True

			if right[-1] < total_pages:
				last = True
		elif page_number == total_pages:
			# 假如共4页，page_range[1]是第二个元素，page_range[3]代表第四个元素，但是不取
			# 假如3页，page_range[0]
			# 假如2页，page_range[-1]
			left = page_range[(page_number-3) if (page_number-3) > 0 else 0:page_number-1]

			if left[0] > 2:
				left_has_more = True

			if left[0] > 1:
				first = True
		else:
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
			right = page_range[page_number:page_number + 2]
			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True

		data = {
			'left': left,
			'right': right,
			'left_has_more': left_has_more,
			'right_has_more': right_has_more,
			'first': first,
			'last': last,
		}
		return data


class CategoryView(IndexView):
	def get_queryset(self):
		cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
		return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(IndexView):
	def get_queryset(self):
		tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
		return super(TagView, self).get_queryset().filter(tags=tag)


class ArchivesView(IndexView):
	def get_queryset(self):
		year = self.kwargs.get('year')
		month = self.kwargs.get('month')
		return super(ArchivesView, self).get_queryset().filter(created_time__year=year, created_time__month=month)


class PostDetailView(DetailView):
	model = Post
	template_name = 'blog/detail.html'  #detail.html
	context_object_name = 'post'

	def get(self, request, *args, **kwargs):
		response = super(PostDetailView, self).get(request, *args, **kwargs)
		self.object.increase_views()
		return response

	# def get_object(self, queryset=None):
	# 	post = super(PostDetailView, self).get_object(queryset=None)
	# 	post.body = markdown.markdown(post.body, extensions=[
	# 		'markdown.extensions.extra',
	# 		'markdown.extensions.codehilite',
	# 		'markdown.extensions.toc'
	# 	])
	# 	return post

	def get_object(self, queryset=None):
		post = super(PostDetailView, self).get_object(queryset=None)
		md = markdown.Markdown(extensions=[
			'markdown.extensions.extra',
			'markdown.extensions.codehilite',
			TocExtension(slugify=slugify),
		])
		post.body = md.convert(post.body)
		post.toc = md.toc

		return post

	def get_context_data(self, **kwargs):
		context = super(PostDetailView, self).get_context_data(**kwargs)
		form = CommentForm()
		comment_list = self.object.comment_set.all()
		context.update({
			'form': form,
			'comment_list': comment_list
		})
		return context


# class PostDetailView(DetailView):
#     model = Post
#     template_name = 'blog/detail.html'
#     context_object_name = 'post'
#
#     def get(self, request, *args, **kwargs):
#         # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
#         # get 方法返回的是一个 HttpResponse 实例
#         # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
#         # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
#         response = super(PostDetailView, self).get(request, *args, **kwargs)
#
#         # 将文章阅读量 +1
#         # 注意 self.object 的值就是被访问的文章 post
#         self.object.increase_views()
#
#         # 视图必须返回一个 HttpResponse 对象
#         return response
#
#     def get_object(self, queryset=None):
#         # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
#         post = super(PostDetailView, self).get_object(queryset=None)
#         post.body = markdown.markdown(post.body,
#                                       extensions=[
#                                           'markdown.extensions.extra',
#                                           'markdown.extensions.codehilite',
#                                           'markdown.extensions.toc',
#                                       ])
#         return post
#
#     def get_context_data(self, **kwargs):
#         # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
#         # 还要把评论表单、post 下的评论列表传递给模板。
#         context = super(PostDetailView, self).get_context_data(**kwargs)
#         form = CommentForm()
#         comment_list = self.object.comment_set.all()
#         context.update({
#             'form': form,
#             'comment_list': comment_list
#         })
#         # return context


# def detail(request, pk):
# 	post = get_object_or_404(Post, pk=pk)
#
# 	post.increase_views()
#
# 	post.body = markdown.markdown(post.body, extensions=[
# 		'markdown.extensions.extra',
# 		'markdown.extensions.codehilite',
# 		'markdown.extensions.toc',
# 	])
# 	form = CommentForm()
# 	comment_list = post.comment_set.all()
# 	context = {
# 		'post': post,
# 		'form': form,
# 		'comment_list': comment_list
# 	}
# 	# 绑定的是detail页面url
# 	return render(request, 'blog/detail.html', context=context)


# def archives(request, year, month):
# 	post_list = Post.objects.filter(created_time__year=year, created_time__month=month)
# 	return render(request, 'blog/index.html', context={'post_list': post_list})

templates/blog/datail.html
{% extends 'base.html' %}

{% block main %}

    <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.body|safe }}
                    </div>
                </article>
    <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ form.text.id_for_label }}">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>

                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            暂无评论
                            {% endfor %}

                        </ul>
                    </div>
                </section>

{% endblock main %}

{% block toc %}
    <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    <ul>
                        <li>
                            <a href="#">教程特点</a>
                        </li>
                        <li>
                            <a href="#">谁适合这个教程</a>
                        </li>
                        <li>
                            <a href="#">在线预览</a>
                        </li>
                        <li>
                            <a href="#">资源列表</a>
                        </li>
                        <li>
                            <a href="#">获取帮助</a>
                        </li>
                    </ul>
                </div>

{% endblock toc %}

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}

    <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.body|safe }}
                    </div>
                </article>
    <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ form.text.id_for_label }}">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>

                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            暂无评论
                            {% endfor %}

                        </ul>
                    </div>
                </section>

{% endblock main %}

{% block toc %}
    <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
{#                    <ul>#}
{#                        <li>#}
                            <a href="#">{{ post.toc|safe }}</a>
{#                        </li>#}
{#                    </ul>#}
                </div>

{% endblock toc %}
{% block tag %}
                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% for tag in post.tags.all %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
{% endblock tag %}

templates/blog/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags %}

{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
{#                            <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>#}
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                <div class="no-post">暂时还没有发布的文章！</div>
                {% endfor %}
                <!-- 简单分页效果-->
{#                {% if is_paginated %}#}
{#                <div class="pagination-simple">#}
{#                    {% if page_obj.has_previous %}#}
{#                    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>#}
{#                    {% endif %}#}
{#                    <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>#}
{#                    {% if page_obj.has_next %}#}
{#                    <a href="?page={{ page_obj.next_page_number }}">下一页</a>#}
{#                    {% endif %}#}
{#                </div>#}
{#                {% endif %}#}
                {% if is_paginated %}
                <div class="pagination">
                    <ul>
                        {% if first %}
                        <li><a href="?page=1">1</a></li>
                        {% endif %}

                        {% if left %}
                            {% if left_has_more %}
                        <li><a href="">...</a></li>
                            {% endif %}

                            {% for i in left %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                        {% endif %}

                        <li class="current"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>

                        {% if right %}
                            {% for i in right %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}

                            {% if right_has_more %}
                        <li><a href="">...</a></li>
                            {% endif %}

                        {% endif %}

                        {% if last %}
                        <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                        {% endif %}
                    </ul>
                </div>
                {% endif %}

{% endblock main %}

{% block tag %}
                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
{% endblock tag %}